### ISSUE TITLE
can i use it to split webqsp?

### ISSUE THREAD

**Issue by lgxccc** [semantic-systems/KGQA-datasets-generalization#2]
I noticed that you processed 3 datasets. How can i handle the webqsp dataset? According to the paper, splitting datasets needs schema terms, but i can't find anything about webqsp's schema terms. I sincerely hope that you can provide a brief introduction, please.  p.s. I want to divide the webqsp dataset into four different domains by using your method. Do you think it's feasible?

**Comment by LongquanJiang** [comment]
Hi, first of all, thank you for your question.
According to its definition, schema terms would be the relations (or predicates), classes, and operators in a QA dataset. They are extracted from the sparql queries. You can find how to extract them in preprocess.py, for LCQuAD, LCQuAD2 or QALD. Therefore, if a dataset provides sparql queries for a question, you can use the code to do generalization test. For WebQSP, you must write specific code to first extract schema terms from sparql queries, and then run the resplit.py code. 
Please feel free to contact me if you have any question further.
